defaults:
  - model: protogcn
  - data: basic
  - _self_
  - optional experiment: null

name: exercise
work_dir: null

seed: null
deterministic: false
compile: false

validate: true
test_last: false
test_best: true
auto_resume: true
resume_from: null
load_from: ${oc.env:PRETRAINED,}

total_epochs: 150

optimizer: 
  lr: 0.025
  momentum: 0.9
  weight_decay: 0.0005
  nesterov: true

lr_config:
  min_lr: 0.0

early_stopping:
  patience: 10

evaluation:
  interval: 5
  metrics: [top_k_accuracy, mean_class_accuracy]
  topk: [1, 5]

checkpoint_config: 
  interval: 5

log_config:
  interval: 100


